// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm58IOBx3w7NEfXwvmeFp0H1kN8lKtZuA',
    appId: '1:537229011594:web:7b763279f9b59d6747db73',
    messagingSenderId: '537229011594',
    projectId: 'flutterchat-cb066',
    authDomain: 'flutterchat-cb066.firebaseapp.com',
    storageBucket: 'flutterchat-cb066.appspot.com',
    measurementId: 'G-7N0PNS23PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA34hXmuerz0zRuY9yXDBgDOG9j39Po_3k',
    appId: '1:537229011594:android:522cc743bd3ac65547db73',
    messagingSenderId: '537229011594',
    projectId: 'flutterchat-cb066',
    storageBucket: 'flutterchat-cb066.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5YVb8_FkHy9ZsHR6Aq5wZ1GYXle4kPKE',
    appId: '1:537229011594:ios:bf08bf11d13d1dc047db73',
    messagingSenderId: '537229011594',
    projectId: 'flutterchat-cb066',
    storageBucket: 'flutterchat-cb066.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5YVb8_FkHy9ZsHR6Aq5wZ1GYXle4kPKE',
    appId: '1:537229011594:ios:bf08bf11d13d1dc047db73',
    messagingSenderId: '537229011594',
    projectId: 'flutterchat-cb066',
    storageBucket: 'flutterchat-cb066.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm58IOBx3w7NEfXwvmeFp0H1kN8lKtZuA',
    appId: '1:537229011594:web:3e614b3822e467e547db73',
    messagingSenderId: '537229011594',
    projectId: 'flutterchat-cb066',
    authDomain: 'flutterchat-cb066.firebaseapp.com',
    storageBucket: 'flutterchat-cb066.appspot.com',
    measurementId: 'G-S02DPBZNR3',
  );
}
